<a href="https://colab.research.google.com/github/heyanugrah/pytorch/blob/main/pydata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!pip install torch

In [13]:
import torch
matrix = torch.tensor([[1,2],[1,2]])

In [14]:
matrix.ndim #no of square bracket

2

In [15]:
#scalar
scalar = torch.tensor(7)
scalar.ndim

0

In [16]:
scalar.item() #get item as int

7

In [18]:
vector.shape

torch.Size([2, 2])

In [19]:

matrix = torch.tensor([[1,2],[1,2]])

In [21]:
matrix.ndim

2

In [22]:
matrix3D = torch.tensor([[[1,2],[1,2]]])
matrix3D

tensor([[[1, 2],
         [1, 2]]])

In [23]:
matrix3D.ndim

3

In [25]:
matrix4D = torch.tensor([[[[1,2],[1,2]]]])
matrix4D.ndim

4

In [27]:
#random tensors

In [28]:
random_tensor = torch.rand(2)

In [29]:
random_tensor

tensor([0.3736, 0.4255])

In [32]:
d2randomTensor = torch.rand(2,3)
d2randomTensor

tensor([[0.2084, 0.7783, 0.1655],
        [0.3001, 0.6667, 0.1012]])

In [35]:
d3randomTensor = torch.rand(13,4)
d3randomTensor.shape


torch.Size([13, 4])

In [36]:
#dimension in random tensor

In [37]:
t2d = torch.rand(1,2,2)

In [40]:
t2d


tensor([[[0.4693, 0.1071],
         [0.7461, 0.5650]]])

In [58]:
t3d = torch.rand(1,1,1,1,2,3,4)
t3d.ndim #7 dimension tensor


7

In [59]:
t3d.shape


torch.Size([1, 1, 1, 1, 2, 3, 4])

In [60]:
t3dimage = torch.rand(256,256,3)  #image

In [61]:
t3dimage

tensor([[[0.2255, 0.7484, 0.9487],
         [0.5912, 0.9534, 0.5002],
         [0.0566, 0.1347, 0.0672],
         ...,
         [0.7302, 0.3659, 0.0503],
         [0.2551, 0.3881, 0.6743],
         [0.2173, 0.8662, 0.7370]],

        [[0.4709, 0.5600, 0.1541],
         [0.1235, 0.3187, 0.3616],
         [0.9592, 0.4029, 0.4540],
         ...,
         [0.9824, 0.2352, 0.1120],
         [0.2706, 0.3574, 0.1206],
         [0.2482, 0.5374, 0.5004]],

        [[0.0278, 0.5007, 0.3628],
         [0.0667, 0.0575, 0.8875],
         [0.6201, 0.6224, 0.6112],
         ...,
         [0.7050, 0.5136, 0.0087],
         [0.2392, 0.4586, 0.8707],
         [0.7388, 0.1542, 0.1864]],

        ...,

        [[0.6906, 0.1397, 0.7067],
         [0.3947, 0.4406, 0.6602],
         [0.5788, 0.5477, 0.7105],
         ...,
         [0.1040, 0.1975, 0.6405],
         [0.7441, 0.2647, 0.7758],
         [0.8287, 0.1580, 0.3774]],

        [[0.1905, 0.9640, 0.9576],
         [0.0137, 0.5873, 0.6635],
         [0.

In [63]:
#zeros tensor
zeros = torch.zeros(3,4)

In [64]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
#ones
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [70]:
#arrange
ta = torch.arange(start=0 , end=10, step =1)
ta

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
#like

In [73]:
zl = torch.zeros_like(ta)
zl  #same shape ta

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

tensor datatype

In [75]:
#float32
flt = torch.tensor([1,2,3,4],dtype=torch.float32)
flt

tensor([1., 2., 3., 4.])

In [76]:
flt.dtype

torch.float32

In [85]:
intt = torch.tensor([1,2,3,4],dtype=torch.int64,device=None,requires_grad=False)
intt

int1 = intt.type(torch.float16)
int1.dtype


torch.float16

In [86]:
intt.shape

torch.Size([4])

In [88]:
intt.size() #shape and size both are same

torch.Size([4])

In [90]:
#tensor running which device
intt.device

device(type='cpu')

In [91]:
intt

tensor([1, 2, 3, 4])

In [92]:
tmul  = torch.mul(intt,12)

In [93]:
tmul

tensor([12, 24, 36, 48])

In [94]:
tadd  = torch.add(intt,12)

In [95]:
tadd

tensor([13, 14, 15, 16])

In [96]:
tsub  = torch.sub(intt,12)

In [97]:
tsub

tensor([-11, -10,  -9,  -8])

In [98]:
#multiplication
mtrx = torch.tensor([1,2,3,4])
mtrx*2

tensor([2, 4, 6, 8])

In [99]:
mt1 = torch.tensor([1,2,3,4])
mt2 = torch.tensor([1,2,3,4])
mt1*mt2

tensor([ 1,  4,  9, 16])

In [102]:
mt1 = torch.tensor([[1,2,3,4],[1,2,3,4]])
mt2 = torch.tensor([[1,2],[1,2],[1,2],[1,2]])

m3 = torch.matmul(mt1,mt2)
m3

tensor([[10, 20],
        [10, 20]])

In [103]:
mt1.shape

torch.Size([2, 4])

In [104]:
mt2.shape

torch.Size([4, 2])

In [106]:
%%time
m3.shape

CPU times: user 18 µs, sys: 0 ns, total: 18 µs
Wall time: 23.4 µs


torch.Size([2, 2])

In [109]:
m4 = mt1@mt2 #same like matrix multiplication

In [110]:
m4

tensor([[10, 20],
        [10, 20]])

In [117]:
m1 = torch.rand(2,3)
m2 = torch.rand(3,2)
torch.matmul(m1,m2)



tensor([[1.3474, 1.4602],
        [1.3065, 1.4335]])

In [118]:
m1.shape

torch.Size([2, 3])

In [119]:
tr = m1.T

In [120]:
tr

tensor([[0.9963, 0.9715],
        [0.7689, 0.7332],
        [0.6031, 0.6156]])

In [121]:
tr.shape

torch.Size([3, 2])

In [123]:
x = torch.arange(1,100,10)

In [124]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [125]:
print("min ",torch.min(x))
print("max ",torch.max(x))

min  tensor(1)
max  tensor(91)


In [129]:
torch.mean(x,dtype=torch.float32)

tensor(46.)

In [134]:
torch.mean(torch.arange(1,4,1),dtype=torch.float32)

tensor(2.)

In [136]:
torch.sum(torch.arange(1,4,1))

tensor(6)

In [137]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [138]:
x.argmin()

tensor(0)

In [139]:
x.argmax()

tensor(9)

In [140]:
x[0]

tensor(1)

In [141]:
x[9]

tensor(91)

In [142]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [143]:
#reshaping

In [144]:
x.shape

torch.Size([10])

In [153]:
x.reshape(10,1)

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

In [157]:
x.shape

torch.Size([10])

In [158]:
x.view(2,5)

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])

In [159]:
x.view(5,2)

tensor([[ 1, 11],
        [21, 31],
        [41, 51],
        [61, 71],
        [81, 91]])

In [160]:
x.view(1,10)

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [161]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [162]:
x.view(10,1)

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

In [163]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [164]:
y = torch.arange(1,10,1)

In [172]:
stk = torch.stack([x[:9],y],dim=0)

In [173]:
stk

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [175]:
vstk = torch.vstack([x[:9],y])

In [176]:
vstk

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [177]:
hstk = torch.hstack([x[:9],y])
hstk

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [182]:
dstk = torch.stack([x[:9],y],dim=0)

In [183]:
dstk

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [186]:
x = torch.zeros(2, 1, 2, 2, 2)
x


tensor([[[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]]])

In [188]:
x.size()

torch.Size([2, 1, 2, 2, 2])

In [193]:
y = torch.squeeze(x)

y

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

In [190]:
y.size()

torch.Size([2, 2, 2, 2])

In [191]:
m = torch.squeeze(x)

In [192]:
m

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

In [194]:
x = torch.randn(2, 3, 5)
x.size()


torch.Size([5, 2, 3])

In [195]:
x

tensor([[[-0.1352,  0.4815, -0.4953,  1.1687, -0.2190],
         [-0.8931, -0.1767,  0.2350, -0.7079, -0.5887],
         [-1.5639,  1.5840, -0.9649, -1.2429,  1.8905]],

        [[-0.2318,  0.0784,  0.3950,  0.9707,  0.6307],
         [ 1.4690, -1.7640,  0.7883,  0.3448, -0.3389],
         [-2.5461,  0.4991, -0.5587, -0.1727, -1.0649]]])

In [196]:
y = torch.permute(x, (2, 0, 1)).size()

In [197]:
y

torch.Size([5, 2, 3])

In [204]:


# create a tensor of size 2 x 4
input_var = torch.randn(2,4)

# print size
print(input_var.size())

print(input_var)

# dimensions permuted
input_var = input_var.permute(1, 0)

# print size
print(input_var.size())

print(input_var)

torch.Size([2, 4])
tensor([[-0.4384,  0.1360,  0.5509,  1.1736],
        [ 0.0204,  0.5412, -0.8611, -0.4412]])
torch.Size([4, 2])
tensor([[-0.4384,  0.0204],
        [ 0.1360,  0.5412],
        [ 0.5509, -0.8611],
        [ 1.1736, -0.4412]])


In [205]:
# import pytorch library
import torch

# create a tensor of size 2 x 4
input_var = torch.randn(2,4)

# print size
print(input_var.size())

print(input_var)

# dimensions permuted
input_var = input_var.permute(-1, 0)

# print size
print(input_var.size())

print(input_var)

torch.Size([2, 4])
tensor([[ 1.1035, -2.0876,  1.2188,  0.2509],
        [ 0.4424,  0.1100,  0.3168,  0.0542]])
torch.Size([4, 2])
tensor([[ 1.1035,  0.4424],
        [-2.0876,  0.1100],
        [ 1.2188,  0.3168],
        [ 0.2509,  0.0542]])


In [206]:
x

tensor([[[-0.1352,  0.4815, -0.4953,  1.1687, -0.2190],
         [-0.8931, -0.1767,  0.2350, -0.7079, -0.5887],
         [-1.5639,  1.5840, -0.9649, -1.2429,  1.8905]],

        [[-0.2318,  0.0784,  0.3950,  0.9707,  0.6307],
         [ 1.4690, -1.7640,  0.7883,  0.3448, -0.3389],
         [-2.5461,  0.4991, -0.5587, -0.1727, -1.0649]]])

In [207]:
ten = torch.arange(1,10,1)

In [208]:
ten


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
ten[0]

tensor(1)

In [210]:
ten[8]

tensor(9)

In [211]:
mt1

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [214]:
mt1[1,2]

tensor(3)

In [217]:
m3d = torch.tensor([[10,9,8,8],[7,8,6,5],[4,6,7,9]])

In [218]:
m3d

tensor([[10,  9,  8,  8],
        [ 7,  8,  6,  5],
        [ 4,  6,  7,  9]])

In [219]:
m3d.ndim

2

In [221]:
m3d[1][2]

tensor(6)

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [223]:
m3d1 = torch.tensor([[10,9,8,8],[7,8,6,5]])

In [225]:
m3dx = torch.tensor([[[10,9,8,8],[7,8,6,5],[4,6,7,9]],[[11,9,8,8],[7,8,6,5],[4,6,7,9]]])

In [231]:
m3dx[0][0][0]

tensor(10)

In [236]:
m3dx[0][1][0]

tensor(7)

In [238]:
d3 = torch.tensor([[[10,9,8,8],[7,8,6,5],[8,8,6,5]]])

In [241]:
d3[0][1][0]

tensor(7)

In [253]:
d3 = torch.tensor([[[[10,9,8,8],[7,8,6,5],[8,8,6,5]]],[[[12,9,8,8],[17,8,6,5],[18,8,6,5]]]])
d3[1][0][0][0]

tensor(12)

In [254]:
d3

tensor([[[[10,  9,  8,  8],
          [ 7,  8,  6,  5],
          [ 8,  8,  6,  5]]],


        [[[12,  9,  8,  8],
          [17,  8,  6,  5],
          [18,  8,  6,  5]]]])

In [255]:
d3.ndim

4

In [256]:
d3[0][0][0][0]

tensor(10)

In [258]:
d3[1][0][0][1]

tensor(9)

In [261]:
d3[:,:,:,1]

tensor([[[9, 8, 8]],

        [[9, 8, 8]]])

In [262]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [268]:
torch.manual_seed(RANDOM_SEED)
print(torch.rand(3,4))
torch.manual_seed(RANDOM_SEED)
print(torch.rand(3,4))

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [269]:
#GPU

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
device

'cuda'

In [4]:
#count no of gpu

In [5]:
torch.cuda.device_count()

1